version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./..:/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
    depends_on:
      - php

  php:
    build:
      context: ./php
    working_dir: /app
    volumes:
      - ../:/app
